version: '3.3'
services:
  bot:
    build:
      context: ./
    depends_on:
      - db
    restart: always
    environment:
      DCtoken: ${DISCORD_BOT_TOKEN}
      DBhost: db
      DBdatabase: ivn
      DBusername: ivn
      DBpassword: ${DB_PASSWORD}

  db:
    image: mariadb:latest
    restart: always
    ports:
      - "${DB_IP}:${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ivn
      MYSQL_USER: ivn
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:

