version: '3.3'
services:
  bot:
    build:
      context: ./
    depends_on:
      - db
    restart: always
    environment:
      DCtoken: ${DISCORD_BOT_TOKEN}
      DBhost: db
      DBusername: ivn
      DBpassword: ${DB_PASSWORD}

  db:
    image: postgres:15
    restart: always
    ports:
      - '${DB_IP}:${DB_PORT}:3306'
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ivn
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
